// apps/web/src/pages/Login.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-slate-900 p-4">
    <div class="w-full max-w-sm bg-white rounded-2xl shadow-xl p-7">
      <h1 class="text-xl font-bold">CRM Suite</h1>
      <p class="text-sm text-slate-500 mb-5">Masuk ke akun perusahaan kamu</p>
      <form @submit.prevent="submit" class="space-y-3">
        <div>
          <label class="label">Email</label>
          <input v-model="email" type="email" required class="input" placeholder="nama@perusahaan.co.id" />
        </div>
        <div>
          <label class="label">Password</label>
          <input v-model="password" type="password" required class="input" />
        </div>
        <div v-if="companies.length">
          <label class="label">Pilih perusahaan</label>
          <select v-model="companyId" class="input">
            <option v-for="c in companies" :key="c.company_id" :value="c.company_id">{{ c.company_id }}</option>
          </select>
        </div>
        <p v-if="error" class="text-red-600 text-sm">{{ error }}</p>
        <button class="btn-primary w-full" :disabled="loading">{{ loading ? "Memproses..." : "Masuk" }}</button>
      </form>
    </div>
  </div>
</template>
<script setup lang="ts">
import { ref } from "vue";
import { useRouter } from "vue-router";
import { useAuthStore } from "../stores/auth";

const auth = useAuthStore();
const router = useRouter();
const email = ref("");
const password = ref("");
const companyId = ref("");
const companies = ref<{ company_id: string }[]>([]);
const error = ref("");
const loading = ref(false);

async function submit() {
  error.value = "";
  loading.value = true;
  try {
    const r = await auth.login(email.value, password.value, companyId.value || undefined);
    if (r === "choose") {
      companies.value = auth.companies;
      companyId.value = auth.companies[0]?.company_id ?? "";
      error.value = "Email terdaftar di beberapa perusahaan — pilih satu lalu tekan Masuk lagi.";
    } else {
      router.push("/");
    }
  } catch (e) {
    error.value = (e as Error).message;
  } finally {
    loading.value = false;
  }
}
</script>

// src/app/(auth)/login/page.tsx
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import { Button } from '@/components/ui/Button'
import { Input } from '@/components/ui/Input'
import { Card } from '@/components/ui/Card'

export default function LoginPage() {
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [mode, setMode] = useState<'login' | 'register'>('login')
  const [fullName, setFullName] = useState('')
  const router = useRouter()

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    setLoading(true)
    setError('')
    const supabase = createClient()

    try {
      if (mode === 'login') {
        const { error } = await supabase.auth.signInWithPassword({ email, password })
        if (error) throw error
        router.push('/contacts')
        router.refresh()
      } else {
        const { error: signUpError } = await supabase.auth.signUp({
          email,
          password,
          options: { data: { full_name: fullName } },
        })
        if (signUpError) throw signUpError
        setError('Check your email for confirmation link.')
        setMode('login')
      }
    } catch (err: any) {
      setError(err.message || 'An error occurred')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-background via-secondary/20 to-background p-4">
      <div className="w-full max-w-md space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
        <div className="text-center space-y-2">
          <h1 className="text-4xl font-black bg-gradient-to-r from-primary to-orange-400 bg-clip-text text-transparent">
            Our CRM
          </h1>
          <p className="text-muted-foreground">
            {mode === 'login' ? 'Sign in to your workspace' : 'Create your workspace'}
          </p>
        </div>

        <Card className="p-8 shadow-2xl border-border/50">
          <form onSubmit={handleSubmit} className="space-y-5">
            {mode === 'register' && (
              <div className="space-y-2">
                <label className="text-sm font-bold ml-1">Full Name</label>
                <Input
                  placeholder="John Doe"
                  value={fullName}
                  onChange={(e) => setFullName(e.target.value)}
                  required
                />
              </div>
            )}

            <div className="space-y-2">
              <label className="text-sm font-bold ml-1">Email</label>
              <Input
                type="email"
                placeholder="you@company.com"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                required
              />
            </div>

            <div className="space-y-2">
              <label className="text-sm font-bold ml-1">Password</label>
              <Input
                type="password"
                placeholder="••••••••"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                required
                minLength={6}
              />
            </div>

            {error && (
              <div className="bg-destructive/10 text-destructive text-sm font-medium px-4 py-3 rounded-xl">
                {error}
              </div>
            )}

            <Button type="submit" isLoading={loading} className="w-full h-12 text-base">
              {mode === 'login' ? 'Sign In' : 'Create Account'}
            </Button>
          </form>

          <div className="mt-6 text-center">
            <button
              type="button"
              onClick={() => {
                setMode(mode === 'login' ? 'register' : 'login')
                setError('')
              }}
              className="text-sm text-muted-foreground hover:text-primary transition-colors font-medium"
            >
              {mode === 'login'
                ? "Don't have an account? Register"
                : 'Already have an account? Sign in'}
            </button>
          </div>
        </Card>
      </div>
    </div>
  )
}
