// web/src/lib/components/ui/Button.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { HTMLButtonAttributes } from 'svelte/elements';
	import { cn } from '$lib/utils';

	type Variant = 'solid' | 'outline' | 'ghost' | 'danger';
	type Size = 'sm' | 'md' | 'icon';

	type Props = HTMLButtonAttributes & {
		variant?: Variant;
		size?: Size;
		children?: Snippet;
	};

	let {
		variant = 'solid',
		size = 'md',
		class: cls = '',
		type = 'button',
		children,
		...rest
	}: Props = $props();

	const variants: Record<Variant, string> = {
		solid: 'bg-neon text-on-neon hover:bg-neon-strong shadow-[0_0_14px_var(--neon-glow)]',
		outline: 'border border-line bg-surface text-ink hover:border-neon hover:text-neon-text',
		ghost: 'text-muted hover:bg-raised hover:text-ink',
		danger: 'border border-transparent bg-danger-soft text-danger hover:bg-danger hover:text-white'
	};

	const sizes: Record<Size, string> = {
		sm: 'h-8 gap-1.5 rounded-md px-3 text-xs',
		md: 'h-9.5 gap-2 rounded-lg px-4 text-sm',
		icon: 'size-9 rounded-lg'
	};
</script>

<button
	{type}
	class={cn(
		'inline-flex shrink-0 cursor-pointer items-center justify-center font-medium transition-colors duration-150 disabled:pointer-events-none disabled:opacity-50',
		variants[variant],
		sizes[size],
		cls
	)}
	{...rest}
>
	{@render children?.()}
</button>

// src/components/ui/Button.tsx
import { cn } from "@/lib/utils";
import { ButtonHTMLAttributes, forwardRef } from "react";

interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: "primary" | "secondary" | "outline" | "ghost" | "destructive";
  size?: "sm" | "md" | "lg" | "icon";
  isLoading?: boolean;
}

const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant = "primary", size = "md", isLoading, children, disabled, ...props }, ref) => {
    const variants = {
      primary: "bg-primary text-primary-foreground shadow-lg shadow-primary/20 hover:bg-primary/90",
      secondary: "bg-secondary text-secondary-foreground hover:bg-secondary/80",
      outline: "border border-border bg-transparent hover:bg-secondary text-foreground",
      ghost: "bg-transparent hover:bg-secondary text-muted-foreground hover:text-foreground",
      destructive: "bg-destructive text-destructive-foreground hover:bg-destructive/90",
    };

    const sizes = {
      sm: "h-9 px-3 text-xs",
      md: "h-10 px-4 py-2 text-sm",
      lg: "h-12 px-6 text-base",
      icon: "h-10 w-10 p-0 justify-center",
    };

    return (
      <button
        ref={ref}
        disabled={disabled || isLoading}
        className={cn(
          "inline-flex items-center justify-center rounded-xl font-bold transition-all active:scale-95 disabled:opacity-50 disabled:pointer-events-none",
          variants[variant],
          sizes[size],
          className
        )}
        {...props}
      >
        {isLoading ? (
          <div className="mr-2 h-4 w-4 animate-spin rounded-full border-2 border-current border-t-transparent" />
        ) : null}
        {children}
      </button>
    );
  }
);

Button.displayName = "Button";

export { Button };
