// web/src/lib/components/ui/Input.svelte
<script lang="ts">
	import type { HTMLInputAttributes } from 'svelte/elements';
	import { cn } from '$lib/utils';

	type Props = HTMLInputAttributes & {
		error?: string | null;
		mono?: boolean;
	};

	let { value = $bindable(''), error = null, mono = false, class: cls = '', ...rest }: Props = $props();
</script>

<input
	class={cn(
		'h-9.5 w-full rounded-lg border bg-surface px-3 text-sm text-ink transition-colors',
		'placeholder:text-faint hover:border-line-strong focus:border-neon focus:outline-none',
		'disabled:cursor-not-allowed disabled:opacity-60',
		error ? 'border-danger' : 'border-line',
		mono && 'font-mono text-[13px]',
		cls
	)}
	{...rest}
/>
{#if error}
	<p class="mt-1.5 text-xs text-danger">{error}</p>
{/if}

// src/components/ui/Input.tsx
import { cn } from "@/lib/utils";
import { InputHTMLAttributes, forwardRef } from "react";

export type InputProps = InputHTMLAttributes<HTMLInputElement>;

const Input = forwardRef<HTMLInputElement, InputProps>(
  ({ className, type, ...props }, ref) => {
    return (
      <input
        type={type}
        className={cn(
          "flex h-9 w-full rounded-lg border border-border bg-card px-2.5 py-1.5 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground/70 focus-visible:outline-none focus-visible:border-primary disabled:cursor-not-allowed disabled:opacity-50 transition-colors",
          className
        )}
        ref={ref}
        {...props}
      />
    );
  }
);
Input.displayName = "Input";

export { Input };

export const inputClass =
  "flex h-9 w-full rounded-lg border border-border bg-card px-2.5 py-1.5 text-sm placeholder:text-muted-foreground/70 focus-visible:outline-none focus-visible:border-primary disabled:cursor-not-allowed disabled:opacity-50 transition-colors";
